import { defineMDSveXConfig as defineConfig } from 'mdsvex';
import path from 'path';
import { fileURLToPath } from 'url';
// import remarkAbbr from 'remark-abbr';
// import remarkUnwrapImages from "remark-unwrap-images";
import rehypeUnwrapImages from "rehype-unwrap-images";
// import remarkRelativeImages from "mdsvex-relative-images";
// import remarkContainers from 'remark-containers';
import rehypeSlug from 'rehype-slug';
// import rehypeAutolinkHeadings from 'rehype-autolink-headings';
import remarkRelativeImages from './mdsvexplugins/mdsvex-relative-images.js'
import remarkFrontmatterImport from './mdsvexplugins/mdsvex-frontmatter-to-import.js'
import remarkAutoloadComponents from './mdsvexplugins/mdsvex-import-components.js'
import remarkAutoloadTemplates from './mdsvexplugins/mdsvex-import-templates.js'
// import rehypePrettyCode from "rehype-pretty-code";
// import rehypeCodeTitles from 'rehype-code-titles';
// import rehypeStringify from 'rehype-stringify';
// import {
// 	transformerCopyButton,
// 	transformerFoldableLines,
//   } from '@rehype-pretty/transformers';

// const rehypePrettyCodeOptions = {
// 	theme: 'rose-pine',
// 	transformers: [
// 	//   transformerCopyButton({
// 	// 	visibility: 'always',
// 	// 	feedbackDuration: 2_500,
// 	// 	buttonHTML: '<button class="copy-button"><span class="copy-icon"></span></button>'
// 	//   }),
// 	  transformerFoldableLines({
// 		lines: [[1, 2]],
// 	  }),
// 	],
//   };

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Resolve the absolute path to the layout file
// Using .replace(/\\/g, '/') ensures forward slashes, which are generally safer for import paths,
// though Vite on Windows can often handle backslashes in absolute paths.
const absoluteLayoutPath = path.resolve(__dirname, './src/lib/mdsvex/layouts/default.svelte').replace(/\\/g, '/');


const config = defineConfig({
	layout: {
		_: absoluteLayoutPath
	},
	extensions: ['.svelte.md', '.md', '.svx', '.page'],
	highlight: false,
	smartypants: {
		
	},
	rehypePlugins: [
		// rehypeCodeTitles,
		// [rehypePrettyCode, rehypePrettyCodeOptions],
		// rehypeStringify,
		rehypeSlug, // Add IDs to headings
		// [rehypeAutolinkHeadings, { behavior: 'before' }]
		rehypeUnwrapImages,
	],
	remarkPlugins: [
		// [remarkAbbr, { expandFirst: true }], // parse html abbreviations
		// remarkContainers, // processes `:::`-Tags to html-tags
		// [remarkMermaid, { simple: true }],
		// remarkGfm,
		remarkFrontmatterImport, // looks for 'image' tag in frontmatter and makes them available/imports to page metadata
		// remarkUnwrapImages, // removes p-tags arround images generated by markdown
		remarkRelativeImages, // Imports relative linked images and makes them available to vite imagetools
		remarkAutoloadComponents, // Adds js import scrip for components
		remarkAutoloadTemplates, // Adds js import script for templates
	]
});

export default config;
