import adapter from '@sveltejs/adapter-static';
import { vitePreprocess } from '@sveltejs/kit/vite';

import { mdsvex } from 'mdsvex';
import mdsvexConfig from './mdsvex.config.js';

/** @type {import('@sveltejs/kit').Config} */
const config = {

	extensions: ['.svelte', ...mdsvexConfig.extensions],

	preprocess: [
		mdsvex(mdsvexConfig),
		vitePreprocess(),
	],
	vitePlugin: {
		inspector: {
		  toggleKeyCombo: 'control-y'
		},
	},
	kit: {
		adapter: adapter({
			pages: 'build',
			assets: 'build',
			fallback: '200.html',
			precompress: true
		}),
		prerender: {
			handleHttpError: 'fail',
			entries:  [
				"*",
				"/1",
				"/1/2",
				"/1/2/3",
				"/1/2/3/4",
				"/1/2/3/4/5",
				"/1/2/3/4/5/6",
				"/1.json",
				"/1/2.json",
				"/1/2/3.json",
				"/1/2/3/4.json",
				"/1/2/3/4/5.json",
				"/1/2/3/4/5/6.json",
			]
		},
		files: {
			assets: 'static_autogenerated',
		}
	},

};

export default config;
