import { mdsvex } from 'mdsvex';
import adapter from '@sveltejs/adapter-static';

import mdsvexConfig from './mdsvex.config.js';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		// adapter-auto only supports some environments, see https://svelte.dev/docs/kit/adapter-auto for a list.
		// If your environment is not supported, or you settled on a specific environment, switch out the adapter.
		// See https://svelte.dev/docs/kit/adapters for more information about adapters.
		adapter: adapter({
			pages: 'build',
			assets: 'build',
			fallback: '200.html',
			precompress: true
		}),
		prerender: {
			handleHttpError: 'fail',
			// entries:  [
			// 	"*"
			// ]
		},
		files: {
			assets: 'static_autogenerated',
		},
		inlineStyleThreshold: Infinity
	},

	preprocess: [
		mdsvex(mdsvexConfig)
	],
	extensions: ['.svelte', ...mdsvexConfig.extensions],
	vitePlugin: {
		inspector: {
		  toggleKeyCombo: 'control-y'
		},
	},
};

export default config;
