import adapter from '@sveltejs/adapter-static';
import { vitePreprocess } from '@sveltejs/kit/vite';

import { mdsvex } from 'mdsvex';
import mdsvexConfig from './mdsvex.config.js';

/** @type {import('@sveltejs/kit').Config} */
const config = {

	extensions: ['.svelte', ...mdsvexConfig.extensions],

	preprocess: [
		mdsvex(mdsvexConfig),
		vitePreprocess(),
	],
	vitePlugin: {
		inspector: {
		  toggleKeyCombo: 'control-y'
		},
	},
	kit: {
		adapter: adapter({
			pages: 'build',
			assets: 'build',
			fallback: '200.html',
			precompress: true
		}),
		prerender: {
			handleHttpError: 'fail',
			// entries:  [
			// 	"*"
			// ]
		},
		files: {
			assets: 'static_autogenerated',
		}
	},

};

export default config;
