const fs = require('fs-extra');
const path = require('path');

const srcContentDir = `./src/content`;
const src_Dir = `./static`;
const destDir = `./static_autogenerated`;
const languageFolders = ['en', 'de']; // Languages we support
const mediaExtensions = [
    '.jpg', 
    '.jpeg', 
    '.png', 
    '.gif', 
    '.svg', 
    '.mp4', 
    '.mp3', 
    '.pdf', 
    '.zip'
]; // Media file extensions to handle specially

// Function to find all media files in source directories
function findAllMediaFiles() {
    const mediaFiles = [];
    
    // Helper function to find media files
    function findInDir(dir, baseDir, applyFilter = true) {
        const files = fs.readdirSync(dir);
        
        files.forEach(file => {
            const filePath = path.join(dir, file);
            const stat = fs.statSync(filePath);
            
            if (stat.isDirectory()) {
                findInDir(filePath, baseDir, applyFilter);
            } else {
                const ext = path.extname(file).toLowerCase();
                if (!applyFilter || mediaExtensions.includes(ext)) {
                    mediaFiles.push({
                        src: filePath,
                        relativePath: path.relative(baseDir, filePath)
                    });
                }
            }
        });
    }
    
    // Find media files in content directory (apply filter)
    console.log('Finding media files in content directory...');
    findInDir(srcContentDir, srcContentDir, true);
    
    // Find ALL files in static directory (no filter)
    console.log('Finding all files in static directory...');
    findInDir(src_Dir, src_Dir, false);
    
    console.log(`Found ${mediaFiles.length} total files to copy`);
    return mediaFiles;
}

// Function to apply renaming to a path
function applyRename(filePath) {
    const parts = filePath.split(path.sep);
    const regexRename = /^!?\[\.\.\.[\d]+\]/g;
    
    return parts.map(part => part.replace(regexRename, '')).join(path.sep);
}

// Main execution
console.log('Packing static folder...');

// Clean destination directory
console.log('Delete', destDir);
fs.removeSync(destDir);
fs.ensureDirSync(destDir);

// Find all media files
const allMediaFiles = findAllMediaFiles();

// Create destination folders including language subfolders
languageFolders.forEach(lang => {
    fs.ensureDirSync(path.join(destDir, lang));
});

// Copy content media files to destinations with renamed paths
allMediaFiles.forEach(file => {
    // Create renamed path
    const renamedRelativePath = applyRename(file.relativePath);
    
    // Copy to root destination
    const rootDestPath = path.join(destDir, renamedRelativePath);
    try {
        fs.ensureDirSync(path.dirname(rootDestPath));
        fs.copyFileSync(file.src, rootDestPath);
    } catch (err) {
        console.error(`Error copying to ${rootDestPath}:`, err);
    }
    
    // Copy to each language folder
    languageFolders.forEach(lang => {
        const langDestPath = path.join(destDir, lang, renamedRelativePath);
        try {
            fs.ensureDirSync(path.dirname(langDestPath));
            fs.copyFileSync(file.src, langDestPath);
        } catch (err) {
            console.error(`Error copying to ${langDestPath}:`, err);
        }
    });
});

console.log('Media files copied to all destinations with renamed paths');