#!/usr/bin/env node
/*
 * Watcher for development — reruns prebuild scripts when content or static files change
 * Usage: node ./prebuild/watch.cjs [--no-initial]
 */
const chokidar = require('chokidar');
const { spawn } = require('child_process');
const path = require('path');

const args = process.argv.slice(2);
const skipInitial = args.includes('--no-initial');

const WATCH_GLOBS = [
  path.join(process.cwd(), 'src', 'content'),
  path.join(process.cwd(), 'static'),
  path.join(process.cwd(), 'src', 'lib', 'scripts', 'store.js')
];

const IGNORES = [
  path.join(process.cwd(), 'static_autogenerated'),
  path.join(process.cwd(), 'build'),
  path.join(process.cwd(), 'node_modules'),
  path.join(process.cwd(), '.git'),
  path.join(process.cwd(), 'src', 'sitemap.js')
];

let running = false;
let queued = false;
let debounceTimer = null;

function runSpawn(command, args = []) {
  return new Promise((resolve, reject) => {
    const proc = spawn(command, args, { stdio: 'inherit', shell: false });
    proc.on('error', (err) => reject(err));
    proc.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`Process ${command} ${args.join(' ')} exited with ${code}`));
    });
  });
}

async function runPrebuilds() {
  try {
    console.log('[prebuild:watch] Running packStaticFolder...');
    await runSpawn('node', [path.join('prebuild', 'packStaticFolder', 'index.cjs')]);
  } catch (err) {
    console.error('[prebuild:watch] packStaticFolder failed:', err);
  }

  try {
    console.log('[prebuild:watch] Running generate-subpage-files...');
    await runSpawn('node', [path.join('prebuild', 'generate-subpage-files.cjs')]);
  } catch (err) {
    console.error('[prebuild:watch] generate-subpage-files failed:', err);
  }
}

async function scheduleRun() {
  if (running) {
    queued = true;
    return;
  }

  running = true;
  await runPrebuilds();
  running = false;

  if (queued) {
    queued = false;
    // Give a small delay so rapid changes can be grouped
    debounceTimer = setTimeout(scheduleRun, 100);
  }
}

function onChange(event, filePath) {
  // Log and debounce
  console.log(`[prebuild:watch] ${event} ${filePath}`);

  if (debounceTimer) clearTimeout(debounceTimer);

  debounceTimer = setTimeout(() => {
    scheduleRun().catch(err => console.error('[prebuild:watch] scheduleRun error', err));
  }, 250);
}

console.log('[prebuild:watch] Watching for changes in src/content and static (ignoring static_autogenerated and src/sitemap.js)');

const watcher = chokidar.watch(WATCH_GLOBS, {
  ignored: IGNORES,
  ignoreInitial: true,
  persistent: true,
  followSymlinks: true,
  awaitWriteFinish: { stabilityThreshold: 200, pollInterval: 100 },
});

watcher
  .on('add', (p) => onChange('add', p))
  .on('change', (p) => onChange('change', p))
  .on('unlink', (p) => onChange('unlink', p))
  .on('addDir', (p) => onChange('addDir', p))
  .on('unlinkDir', (p) => onChange('unlinkDir', p))
  .on('error', (err) => console.error('[prebuild:watch] watcher error', err));

async function runInitialIfNeeded() {
  if (skipInitial) {
    console.log('[prebuild:watch] --no-initial flag passed, skipping initial run');
    return;
  }
  console.log('[prebuild:watch] Running initial prebuilds (pack + generate)');
  await scheduleRun();
}

runInitialIfNeeded().catch(err => console.error('[prebuild:watch] initial run failed', err));

function shutdown() {
  console.log('[prebuild:watch] Shutting down watcher');
  if (debounceTimer) clearTimeout(debounceTimer);
  watcher.close().then(() => process.exit(0));
}

process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);
