on: 
  push:
    branches:
      - STAGING
name: 🚀 Deploy staging website on push

jobs:
  web-deploy:
    name: 🎉 Deploy Staging
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/static'
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: subdir/package-lock.json
      
    - name: 🔨 Build Project
      run: |
        npm ci
        pnpm run build
    
    - name: 📂 Sync files
      uses: wangyucode/sftp-upload-action@v1.4.5
      with:
          host: ${{ secrets.FTP_HOST }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PRIVATE_KEY }}
          localDir: './build'
          remoteDir: '/staging'
          exclude: '**/env.php'
          forceUpload: false
          dryRun: false