# .github/workflows/Typesense.yml

# Workflow name
name: 'Typesense'

# Event for the workflow
on: 
  push:
    branches:
      - PRODUCTION

# List of jobs
jobs:
    typesense-scraper:
      runs-on: ubuntu-latest
      steps:
        - name: Await CF Pages
          uses: WalshyDev/cf-pages-await@v1
          with:

            # Use an API token (Recommended!)
            apiToken: ${{ secrets.CF_API_TOKEN }}

            accountId: 'ccad93124cc432ec1764efad18f9ab1c'
            project: 'calliope-docs'
            # Add this if you want GitHub Deployments (see below)
            githubToken: ${{ secrets.GITHUB_TOKEN }}
            # Add this if you want to wait for a deployment triggered by a specfied commit
            commitHash: ${{ steps.push-changes.outputs.commit-hash }}
    
        - name: Checkout Repository
          uses: actions/checkout@v3
      
        - name: Run DocSearch Scraper
          uses: celsiusnarhwal/typesense-scraper@v2
          with:
            api-key: ${{ secrets.TYPESENSE_API_KEY }}
            host: ${{ secrets.TYPESENSE_URL }}
            port: 8108
            protocol: http
            config: docsearch.config.json